// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/amr-dashboard/HudCockpit.tsx": () => import("../components/mockups/amr-dashboard/HudCockpit.tsx"),
  "./components/mockups/amr-dashboard/Terminal.tsx": () => import("../components/mockups/amr-dashboard/Terminal.tsx"),
  "./components/mockups/amr-dashboard/VoidCenter.tsx": () => import("../components/mockups/amr-dashboard/VoidCenter.tsx")
};
